### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by ofirkris** [minhmanho/dpscan#2]
Thanks for your support!

As for training, in the repo there're no dataset generation model nor generated dataset
would be great if you can share: 
1) training code
2) pretrained weights for dataset generation model and/or generated dataset itself

**Comment by minhmanho** [comment]
Hi,

Well-noted.
I didn't have any plan to publish the training code.
Input and Ground-truth have been clarified in the attached image folders so that you can code a simple DataLoader your way.
Besides, data augmentation is described in the paper.
Anyway, sure. I will consider publishing the training code after publishing the improved version.
